### ISSUE TITLE
Support the SQL api

### ISSUE THREAD

**Issue by lookingcloudy** [AntonShuvaev/elasticsearch4idea#110] opened 2023-06-17 19:17 UTC
### Is your feature request related to a problem?

The newer versions of Elastic include a SQL api.  SQL can be used to query elasticsearch, which is very convenient for most developers and analysts.

### Describe the solution you'd like

Your tool should support the SQL api in both the query console and the search filter.

**Comment by AntonShuvaev** [comment] 2023-06-18 19:49
Closing this issue as duplicate of #58

**Closed as not planned by AntonShuvaev** 2023-06-18 19:49 UTC
Labels: enhancement
